//Weapon Object
const WEAPONS = [
  {
    id: 0,
    properties: '',
    element: '0',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 1,
    properties: '',
    element: '0',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 2,
    properties: '0',
    element: '',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 3,
    properties: '',
    element: '1',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 4,
    properties: '',
    element: '3',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 5,
    properties: '',
    element: '1',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 6,
    properties: '',
    element: '2',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 7,
    properties: '',
    element: '3',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 8,
    properties: '',
    element: '1',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 9,
    properties: '',
    element: '2',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 10,
    properties: '',
    element: '3',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 11,
    properties: '',
    element: '1',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 12,
    properties: '',
    element: '3',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 13,
    properties: '',
    element: '2',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
  {
    id: 14,
    properties: '',
    element: '1',
    stat1: '',
    stat1Value: 0,
    stat1Type: 0,
    stat2: '',
    stat2Value: 0,
    stat2Type: 0,
    stat3: '',
    stat3Value: 0,
    stat3Type: 0,
    level: 0,
    blade: '',
    crossguard: '',
    grip: '',
    pommel: '',
    stars: 3,
    lowStarBurnPoints: 0,
    fourStarBurnPoints: 0,
    fiveStarBurnPoints: 0,
    bonusPower: 0
  },
];

export default {
  WEAPONS
};
