//PvP Headers
const ARSENAL_PREPARATION_HEADER_TEXT = 'ARSENAL PREPARATION';
const FIND_OPPONENT_HEADER_TEXT = 'FIND OPPONENT';
const ARENA_HEADER_TEXT = 'ARENA';

//PvP Divider
const CHARACTER_HEADER_TEXT = 'CHARACTER';
const INVENTORY_HEADER_TEXT = 'INVENTORY';

const CHARACTER_HEADER_TEXT_HINT = 'Placeholder text for character hint';
const INVENTORY_HEADER_TEXT_HINT = 'Placeholder text for inventory hint';

//Element Classification
const FIRE_ELEMENT = '0';
const EARTH_ELEMENT= '1';
const LIGHTNING_ELEMENT = '2';
const WATER_ELEMENT = '3';

//NFT Type
const CHARACTER_NFT = '0';
const WEAPON_NFT = '1';
const SHIELD_NFT = '2';


//PvP Inventory Tab Name
const INVENTORY_TAB_NAMES =[
  {id:'0',name:'sword-tab',value:'Sword'},
  {id:'1',name:'shield-tab',value:'Shield'},
];



//Constants for PvP Sword Count
const NUMBER_OF_SWORDS = 16;

export default {
  ARSENAL_PREPARATION_HEADER_TEXT,
  FIND_OPPONENT_HEADER_TEXT,
  ARENA_HEADER_TEXT,
  CHARACTER_HEADER_TEXT,
  INVENTORY_HEADER_TEXT,
  CHARACTER_HEADER_TEXT_HINT,
  INVENTORY_HEADER_TEXT_HINT,
  INVENTORY_TAB_NAMES,
  NUMBER_OF_SWORDS,
  LIGHTNING_ELEMENT,
  WATER_ELEMENT,
  FIRE_ELEMENT,
  EARTH_ELEMENT,
  CHARACTER_NFT,
  WEAPON_NFT,
  SHIELD_NFT,
};
