name: Straight To Prod (Frontend Only)

on: workflow_dispatch

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> test
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: testnet
          github_token: ${{ secrets.MERGE_PERSONAL_ACCESS_TOKEN }}

      - name: Merge dev -> prod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: production
          github_token: ${{ secrets.MERGE_PERSONAL_ACCESS_TOKEN }}
